@extends('layouts.app')

@section('title', 'Generation Summary - PM-KUSUM')

@section('content')

    <div class="page-header d-flex justify-content-between align-items-start flex-wrap gap-2">
        <div>
            <h4 class="mb-0">State-wise Solar Generation Summary</h4>
            <div class="subtext">Aggregated RMS generation across all states</div>
        </div>
        <a href="{{ route('farmers.index') }}" class="btn btn-outline-dark btn-sm">&larr; Back to Farmers</a>
    </div>

    <form method="GET" action="{{ route('generation.summary') }}" class="row g-2 mb-3">
        <div class="col-md-4">
            <label class="form-label mb-1">Show data for last:</label>
            <select name="days" class="form-select" onchange="this.form.submit()">
                @foreach([1, 7, 15, 30, 60, 90] as $opt)
                    <option value="{{ $opt }}" @selected($days == $opt)>{{ $opt }} {{ $opt == 1 ? 'day' : 'days' }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-md-8">
            <label class="form-label mb-1">Or enter custom range (1-90 days):</label>
            <div class="input-group">
                <input type="number" name="days" min="1" max="90" value="{{ $days }}" class="form-control">
                <button class="btn btn-success" type="submit">Update</button>
            </div>
        </div>
    </form>

    <div class="row mb-4 g-3">
        <div class="col-6 col-md-3">
            <div class="stat-card b-orange">
                <div class="stat-icon">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>
                </div>
                <div class="stat-body">
                    <div class="stat-value">{{ $stats['total_units'] }}</div>
                <div class="stat-label">Total Generation (kWh)</div>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-3">
            <div class="stat-card b-blue">
                <div class="stat-icon">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                </div>
                <div class="stat-body">
                    <div class="stat-value">{{ $stats['total_hours'] }}</div>
                <div class="stat-label">Irrigation Hours</div>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-3">
            <div class="stat-card b-teal">
                <div class="stat-icon">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"/></svg>
                </div>
                <div class="stat-body">
                    <div class="stat-value">{{ number_format($stats['total_water']) }}</div>
                <div class="stat-label">Water Discharge (L)</div>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-3">
            <div class="stat-card b-green">
                <div class="stat-icon">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>
                </div>
                <div class="stat-body">
                    <div class="stat-value">{{ $stats['farmer_count'] }}</div>
                <div class="stat-label">Total Farmers/Pumps</div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5">
            <div class="card chart-card mb-4">
                <div class="chart-card-header">
                    <span class="icon-chip">
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>
                    </span>
                    Total Units Generated by State (kWh)
                </div>
                <div class="chart-card-body">
                    <canvas id="stateChart" height="220"></canvas>
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="card chart-card mb-4">
                <div class="chart-card-header">
                    <span class="icon-chip">
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>
                    </span>
                    Daily Total Generation Trend — last {{ $days }} {{ $days == 1 ? 'day' : 'days' }}
                </div>
                <div class="chart-card-body">
                    <canvas id="trendChart" height="220"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="card chart-card mb-4">
        <div class="chart-card-header">
            <span class="icon-chip">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="9" x2="21" y2="9"/></svg>
            </span>
            State-wise Data Table
        </div>
        <div class="chart-card-body">
            <div class="table-responsive">
                <table class="table table-bordered bg-white">
                    <thead class="table-success">
                        <tr>
                            <th>State</th>
                            <th>Total Units Generated (kWh)</th>
                            <th>Total Irrigation Hours</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($byState as $row)
                            <tr>
                                <td>{{ $row->state }}</td>
                                <td>{{ number_format($row->total_units, 2) }}</td>
                                <td>{{ number_format($row->total_hours, 1) }}</td>
                            </tr>
                        @empty
                            <tr><td colspan="3" class="text-center text-muted">No data available.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
    <script>
        const stateLabels = @json($byState->pluck('state'));
        const stateUnits = @json($byState->pluck('total_units')->map(fn($v) => round((float) $v, 2)));

        new Chart(document.getElementById('stateChart'), {
            type: 'bar',
            data: {
                labels: stateLabels,
                datasets: [{
                    label: 'Units Generated (kWh)',
                    data: stateUnits,
                    backgroundColor: ['#2F6FE0', '#F97316', '#16A34A', '#06B6D4'],
                    borderRadius: 6,
                    maxBarThickness: 40,
                }]
            },
            options: {
                responsive: true,
                plugins: { legend: { display: false } },
                scales: {
                    x: { grid: { display: false } },
                    y: { beginAtZero: true, grid: { color: '#EEF2F1' }, title: { display: true, text: 'kWh' } }
                }
            }
        });

        const trendLabels = @json($trendLabels);
        const trendUnits = @json($trendUnits);
        const summaryTrendCtx = document.getElementById('trendChart').getContext('2d');
        const summaryTrendGradient = summaryTrendCtx.createLinearGradient(0, 0, 0, 220);
        summaryTrendGradient.addColorStop(0, 'rgba(47,111,224,0.30)');
        summaryTrendGradient.addColorStop(1, 'rgba(139,92,246,0.03)');

        new Chart(summaryTrendCtx, {
            type: 'line',
            data: {
                labels: trendLabels,
                datasets: [{
                    label: 'Total Units Generated (kWh)',
                    data: trendUnits,
                    borderColor: '#2F6FE0',
                    backgroundColor: summaryTrendGradient,
                    borderWidth: 2.5,
                    fill: true,
                    tension: 0.35,
                    pointRadius: trendLabels.length > 45 ? 0 : 3,
                    pointBackgroundColor: '#2F6FE0',
                }]
            },
            options: {
                responsive: true,
                plugins: { legend: { display: false } },
                scales: {
                    x: { grid: { display: false } },
                    y: { beginAtZero: true, grid: { color: '#EEF2F1' }, title: { display: true, text: 'kWh' } }
                }
            }
        });
    </script>

@endsection
